### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by swarnim1411** [Vedant-Bhalgama/Dr0pFi#5]
Let's say that I want to find my neighbor's password for miscellaneous resasons. So, does my device needs to be inside  the neighbor's network range or will I have to connect, then disconnect and then run the script???

**Comment by Vedant-Bhalgama** [comment]
No ... All you have to do is Deliver the Dr0pFi Payload to your neighbor ... Also you will have to make sure that your neighbor is connected to Internet ... As they execute the script ... You will get a mail consisting WiFI Passwords and SSID's 

**Remember, Don't do any black hat stuff, I won't be responsible for anything!**
