### ISSUE TITLE
FOUND THIS ERROR 

### ISSUE THREAD

**Issue by 9993rills** [Vedant-Bhalgama/Dr0pFi#7]
Nice work, really sick... found this error btw
![Screenshot_3](https://user-images.githubusercontent.com/84611223/126596696-1f708846-d1c4-4d96-809c-25a0ad111fbf.jpg)

**Comment by Vedant-Bhalgama** [comment]
Hi!
I have updated the code, You need Python2 to run this, I'll be updating this soon to Python 3. Sorry!

**Comment by Vedant-Bhalgama** [comment]
Clone once again and run, If error occurs, Please report! Thanks!
